# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c266f6e12c333aad0573b074947aa8161dcbe7142e02636669ee27e391ce4f1f433f977e82b00fa409a16f69835f6d7b60ebc5d0bd2fd197da1efc8bd9a29414

test:
  secret_key_base: 7829e0e2f205300a942abceba85af07dd36d03c31b9843faee62861885ef423cdf23f1ec76a5d6bc90fc1cad4518f3d314b821f33c0db6bfcf81d5a38743f87c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
